
# BasicCAD

We are creating a caster.

---
## Table of Contents
* [Table of Contents](#Table-of-Contents)
* [Base](#Base)
* [Mount](#Mount)
* [Fork](#Fork)
* [Tire](#Tire)
* [Wheel](#Wheel)
* [AxleCollarBearings](#AxleCollarBearings)

## Base

### Description

The first assignment is to create the caster base.  The base's dimensions are 200 mm x 120 mm and 8 mm thick.  It has 6 holes 10 mm wide and 20 mm from the edge equally spaced along the edges. 25mm wide center hole.

### Evidence
[The Base in Onshape](https://cvilleschools.onshape.com/documents/220e283b758f19cc0b5e016e/w/b99eaa03907efb32ba77c17f/e/48e37ca861b914e94113693a)

### Image
This is how you will write image code for INTERNALLY STORED images on your repo.   just FYI.
~~~
<img src="images/Base.jpg" alt="The Base" width="200">
~~~
<img src="https://github.com/OneCHSEngr/BasicCAD/blob/master/images/Base.jpg" width="100">

### Reflection

This was my first Onshape part and [following along with Dr. Shields made it super easy.](https://www.youtube.com/watch?v=93BFUD-HAG8&feature=emb_title&scrlybrkr=5670f0b4) To be honest,I don't feel that I learned any new things. On the otherhand I feel basic familarty and sense of fuidity increase (short cut keys)
Onshape is really nice and renaming sketches is very helpful. 

---


## Mount

### Description

The Second part is a mount to attach to the base for the next part. The dimensions are 100mm x 100mm and 8mm thick. There are 4 10mm wide holes 20mm from edge in each corner and a 25mm wide center hole

### Evidence

[The Mount in Onshape](https://cvilleschools.onshape.com/documents/220e283b758f19cc0b5e016e/w/b99eaa03907efb32ba77c17f/e/48e37ca861b914e94113693a)

### Image

<img src="https://github.com/lmcmind85/GitHub-Basic_Onshape_CAD/blob/master/Screenshot%202020-09-29%20at%2012.50.58%20PM.png?raw=true" width="100">


### Reflection

This part was very similar the part prior and took little time. While creating the first extrude selecting *new* will make it as whole new part in the same Onshape document. I almost missed this and it would have caused furture problems for me.

---


## Fork

### Description

The third part is a Fork to be attched to the mount and hold the wheel. The Main Circle is 80mm and 8mm thick. The Arms are and 40mm by 5 mm rectangle 15 mm from the origin extruded 75 mm. 15mm fillets on top edges of arms extrude. 1mm fillets on edges of prior fillet. 5mm fillet on bottom edged of Arms extrude. Arm is mirrored over Front Plane. 10mm hole 15mm from top of arm through all. Pole is made by a 20mm and a 5mm circle on other side of the Main Circle concentric to origin,then extruded. Champfer Main circle edges and top edge of Pole by 1mm.

### Evidence

[The Fork in Onshape](https://cvilleschools.onshape.com/documents/220e283b758f19cc0b5e016e/w/b99eaa03907efb32ba77c17f/e/48e37ca861b914e94113693a)

### Image

<img src="https://github.com/lmcmind85/BasicCAD/blob/master/Screenshot%202020-10-05%20at%207.10.36%20PM.png?raw=true" width="100">

### Reflection

First uses of Fillet (shift-f), Champfer (None), and mirror (none). I had to rename Extrudes to refer to in description.

---


## Tire

### Description

### Evidence

### Image

### Reflection

---


## Wheel

### Description

### Evidence

### Image

### Reflection

---


## AxleCollarBearings

### Description

### Evidence

### Image

### Reflection

---


